FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app
COPY ./ .


FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /app
COPY --from=build /app/ .

RUN dotnet tool install --global Miccore.Net
RUN dotnet tool install --global dotnet-ef
RUN /root/.dotnet/tools/miccore build --docker

CMD /root/.dotnet/tools/miccore migrate -d /root/.dotnet/tools/dotnet-ef
