FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

COPY ./User.Microservice/User.Microservice/bin/Release/netcoreapp3.1/. .

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app

ENTRYPOINT ["dotnet", "User.Microservice.dll"]
