FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app
COPY ./Gateway.WebApi/bin/Release/netcoreapp3.1/. ./

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
RUN mv ocelot.docker.json ocelot.json
ENTRYPOINT ["dotnet", "Gateway.WebApi.dll"]
