FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app
COPY ./ .


FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app
COPY --from=build /app/ .

RUN dotnet tool install --global Miccore.Net
CMD /root/.dotnet/tools/miccore migrate