FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY ./User.Microservice/bin/Release/net6.0/publish/. .
ENV ASPNETCORE_URLS http://*:80
RUN mkdir wwwroot
ENTRYPOINT ["dotnet", "User.Microservice.dll"]
