FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app
COPY ./bin/Release/net5.0/. .

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /app/. .
RUN mv ocelot.docker.json ocelot.json
ENTRYPOINT ["dotnet", "Gateway.WebApi.dll"]
